name: enthrirhc
description: Enţrirç (Ithkuil Helper)
publish_to: 'none'

version: 0.3.1

environment:
  sdk: '>=3.8.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: 10.2.0
  drift: 2.27.0
  path_provider: 2.1.5
  path: 1.9.1
  provider: 6.1.5
  sqlite3_flutter_libs: 0.5.34
  sqlite3: 2.7.6
  flutter_svg: 2.2.0
  url_launcher: 6.3.1
  shared_preferences: 2.5.3
  flutter_markdown: 0.7.7+1
  package_info_plus: 8.3.0
  vector_graphics: 1.1.19
  prompt_dialog: 1.0.17
  share_plus: 11.0.0
  web: ^1.1.1
  http: ^1.4.0

dev_dependencies:
  flutter_lints: 6.0.0
  drift_dev: 2.27.0
  build_runner: 2.5.4

flutter:
  uses-material-design: true

  assets:
    - assets/icons_compiled/discord.svg.vec
    - assets/icons_compiled/github.svg.vec
    - assets/icons_compiled/reddit.svg.vec
    - assets/icons_compiled/telegram.svg.vec
    - assets/icons_compiled/tencentqq.svg.vec
    - assets/icons_compiled/logo.svg.vec
    # Material Icons
    - assets/icons_compiled/airwave.svg.vec
    - assets/icons_compiled/communities.svg.vec
    - assets/icons_compiled/counter_0.svg.vec
    - assets/icons_compiled/counter_1.svg.vec
    - assets/icons_compiled/counter_2.svg.vec
    - assets/icons_compiled/counter_3.svg.vec
    - assets/icons_compiled/counter_4.svg.vec
    - assets/icons_compiled/counter_5.svg.vec
    - assets/icons_compiled/counter_6.svg.vec
    - assets/icons_compiled/counter_7.svg.vec
    - assets/icons_compiled/counter_8.svg.vec
    - assets/icons_compiled/counter_9.svg.vec
    - assets/icons_compiled/jump_to_element.svg.vec
    - assets/icons_compiled/line_start_circle.svg.vec
    - assets/icons_compiled/list_alt_add.svg.vec
    - assets/icons_compiled/quick_reference_all.svg.vec
    - assets/icons_compiled/shapes.svg.vec
    - assets/icons_compiled/steppers.svg.vec
    - assets/icons_compiled/sweep.svg.vec
    - assets/icons_compiled/transition_fade.svg.vec
  fonts:
    - family: NotoSansItalic
      fonts:
        - asset: assets/fonts/NotoSans-Italic.ttf

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
