enum Aspect {
  rtr,
  prs,
  hab,
  prg,
  imm,
  pcs,
  reg,
  smm,
  atp,
  rsm,
  css,
  pau,
  rgr,
  pcl,
  cnt,
  ics,
  exp,
  irp,
  pmp,
  clm,
  dlt,
  tmp,
  xpd,
  lim,
  epd,
  ptc,
  ppr,
  dcl,
  ccl,
  cul,
  imd,
  trd,
  tns,
  itc,
  mtv,
  sqn;

  String romanize(String charPrecedingThis) {
    return switch (this) {
      rtr => 'a',
      prs => 'ä',
      hab => 'e',
      prg => 'i',
      imm => 'ëi',
      pcs => 'ö',
      reg => 'o',
      smm => 'ü',
      atp => 'u',
      rsm => 'ai',
      css => 'au',
      pau => 'ei',
      rgr => 'eu',
      pcl => 'ëu',
      cnt => 'ou',
      ics => 'oi',
      exp => 'iu',
      irp => 'ui',
      pmp => charPrecedingThis == 'y' ? 'uä' : 'ia',
      clm => charPrecedingThis == 'y' ? 'uë' : 'ie',
      dlt => charPrecedingThis == 'y' ? 'üä' : 'io',
      tmp => charPrecedingThis == 'y' ? 'üë' : 'iö',
      xpd => 'eë',
      lim => charPrecedingThis == 'w' ? 'öë' : 'uö',
      epd => charPrecedingThis == 'w' ? 'öä' : 'uo',
      ptc => charPrecedingThis == 'w' ? 'ië' : 'ue',
      ppr => charPrecedingThis == 'w' ? 'iä' : 'ua',
      dcl => 'ao',
      ccl => 'aö',
      cul => 'eo',
      imd => 'eö',
      trd => 'oë',
      tns => 'öe',
      itc => 'oe',
      mtv => 'öa',
      sqn => 'oa',
    };
  }
}
